# Generated by Django 3.1.4 on 2020-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201220_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_you',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
