# Generated by Django 3.1.4 on 2020-12-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201220_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
