# Generated by Django 3.1.4 on 2020-12-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201221_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_you',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
