# Generated by Django 3.1.4 on 2020-12-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=40)),
                ('img', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banner', models.FileField(upload_to='')),
                ('logo', models.FileField(upload_to='')),
                ('favicon', models.FileField(upload_to='')),
                ('bannertext', models.CharField(max_length=100)),
            ],
        ),
    ]
